# Generated by Django 4.2 on 2025-11-30 20:21

import apps.pacientes.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rut', models.CharField(help_text='RUT del profesional. Formato: 12.345.678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato RUT inválido. Use: 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$'), apps.pacientes.models.validar_rut])),
                ('rol', models.CharField(choices=[('matrona', 'Matrona/Matrón'), ('medico_obstetra', 'Médico Gineco-Obstetra'), ('pediatra', 'Médico Pediatra Neonatología'), ('enfermera_neonatal', 'Enfermera/o Neonatal'), ('puericultura', 'Técnico/a de Puericultura'), ('administrativo', 'Administrativo/a de Servicio'), ('jefe_servicio', 'Jefe/a de Servicio de Obstetricia')], help_text='Rol del usuario en el sistema', max_length=30)),
                ('activo', models.BooleanField(default=True, help_text='Usuario activo en el sistema')),
                ('ultimo_acceso', models.DateTimeField(blank=True, help_text='Fecha y hora del último acceso al sistema', null=True)),
                ('intentos_fallidos', models.IntegerField(default=0, help_text='Número de intentos de login fallidos consecutivos')),
                ('cuenta_bloqueada', models.BooleanField(default=False, help_text='Cuenta bloqueada por intentos fallidos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['rol', 'last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('login', 'Inicio de Sesión'), ('logout', 'Cierre de Sesión'), ('login_fallido', 'Intento de Login Fallido'), ('crear', 'Crear Registro'), ('editar', 'Editar Registro'), ('ver', 'Ver Registro'), ('eliminar', 'Eliminar Registro'), ('exportar', 'Exportar Datos'), ('imprimir', 'Imprimir Documento')], max_length=30)),
                ('modelo', models.CharField(blank=True, help_text='Nombre del modelo afectado (ej: Parto, RecienNacido)', max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, help_text='ID del objeto afectado', null=True)),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción realizada')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Navegador y sistema operativo del usuario')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Estado anterior del objeto (para ediciones)', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Estado nuevo del objeto (para ediciones)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta de la acción')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-timestamp'],
                'permissions': [('view_all_auditoria', 'Puede ver todos los registros de auditoría')],
            },
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['-timestamp'], name='idx_auditoria_timestamp'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['usuario', '-timestamp'], name='idx_auditoria_usuario'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['accion'], name='idx_auditoria_accion'),
        ),
        migrations.AddIndex(
            model_name='auditoria',
            index=models.Index(fields=['modelo', 'objeto_id'], name='idx_auditoria_objeto'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rut'], name='idx_usuario_rut'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['rol'], name='idx_usuario_rol'),
        ),
    ]
