# Generated by Django 4.2 on 2025-12-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False, help_text='Usuario debe cambiar su contraseña en el próximo login'),
        ),
    ]
