# Generated by Django 4.2 on 2025-11-30 22:08

import apps.pacientes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteMadre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(help_text='Formato: 12.345.678-9', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Formato RUT inválido. Use: 12.345.678-9', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]$'), apps.pacientes.models.validar_rut])),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(blank=True, choices=[('soltera', 'Soltera'), ('casada', 'Casada'), ('conviviente', 'Conviviente'), ('viuda', 'Viuda'), ('divorciada', 'Divorciada')], max_length=20)),
                ('escolaridad', models.CharField(blank=True, choices=[('basica_incompleta', 'Básica Incompleta'), ('basica_completa', 'Básica Completa'), ('media_incompleta', 'Media Incompleta'), ('media_completa', 'Media Completa'), ('tecnica', 'Técnica'), ('universitaria_incompleta', 'Universitaria Incompleta'), ('universitaria_completa', 'Universitaria Completa')], max_length=30)),
                ('pueblo_originario', models.BooleanField(default=False, help_text='¿Pertenece a algún pueblo originario?')),
                ('direccion', models.TextField(blank=True)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('prevision', models.CharField(blank=True, choices=[('fonasa_A', 'FONASA A'), ('fonasa_B', 'FONASA B'), ('fonasa_C', 'FONASA C'), ('fonasa_D', 'FONASA D'), ('isapre', 'ISAPRE'), ('particular', 'Particular')], max_length=20)),
                ('consultorio_origen', models.CharField(blank=True, help_text='Consultorio APS de origen', max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente Madre',
                'verbose_name_plural': 'Pacientes Madres',
                'db_table': 'paciente_madre',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pacientemadre',
            index=models.Index(fields=['rut'], name='idx_paciente_rut'),
        ),
        migrations.AddIndex(
            model_name='pacientemadre',
            index=models.Index(fields=['nombre', 'apellido_paterno'], name='idx_paciente_nombre'),
        ),
        migrations.AddIndex(
            model_name='pacientemadre',
            index=models.Index(fields=['comuna'], name='idx_paciente_comuna'),
        ),
    ]
