# Generated by Django 4.2 on 2025-11-30 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecienNacido',
            fields=[
                ('parto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='recien_nacido', serialize=False, to='obstetricia.parto')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('intersexual', 'Intersexual'), ('no_determinado', 'No Determinado')], max_length=20)),
                ('peso_gramos', models.IntegerField(help_text='Peso al nacer en gramos', validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(6000)])),
                ('talla_cm', models.DecimalField(decimal_places=1, help_text='Talla en centímetros', max_digits=4, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(60.0)])),
                ('circunferencia_craneana_cm', models.DecimalField(decimal_places=1, help_text='Circunferencia craneana en cm', max_digits=4, validators=[django.core.validators.MinValueValidator(25.0), django.core.validators.MaxValueValidator(45.0)])),
                ('apgar_1_min', models.IntegerField(help_text='APGAR al minuto 1', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_5_min', models.IntegerField(help_text='APGAR al minuto 5', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('apgar_10_min', models.IntegerField(blank=True, help_text='APGAR al minuto 10 (si aplica)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('reanimacion_requerida', models.BooleanField(default=False)),
                ('tipo_reanimacion', models.CharField(choices=[('ninguna', 'Ninguna'), ('estimulacion', 'Estimulación Táctil'), ('oxigeno', 'Oxígeno'), ('vpp', 'Ventilación a Presión Positiva'), ('intubacion', 'Intubación'), ('masaje_cardiaco', 'Masaje Cardíaco'), ('adrenalina', 'Adrenalina')], default='ninguna', max_length=30)),
                ('destino', models.CharField(choices=[('alojamiento_conjunto', 'Alojamiento Conjunto'), ('neonatologia', 'Neonatología'), ('uci_neonatal', 'UCI Neonatal'), ('traslado', 'Traslado a Otro Centro')], default='alojamiento_conjunto', max_length=30)),
                ('malformaciones', models.BooleanField(default=False)),
                ('descripcion_malformaciones', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Recién Nacido',
                'verbose_name_plural': 'Recién Nacidos',
                'db_table': 'recien_nacido',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoNeonatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('temperatura_celsius', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(34.0), django.core.validators.MaxValueValidator(40.0)])),
                ('frecuencia_cardiaca', models.IntegerField(validators=[django.core.validators.MinValueValidator(60), django.core.validators.MaxValueValidator(200)])),
                ('frecuencia_respiratoria', models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)])),
                ('tipo_alimentacion', models.CharField(blank=True, choices=[('lactancia_materna', 'Lactancia Materna Exclusiva'), ('formula', 'Fórmula'), ('mixta', 'Mixta')], max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='neonatologia.reciennacido')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento Neonatal',
                'verbose_name_plural': 'Seguimientos Neonatales',
                'db_table': 'seguimiento_neonatal',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddIndex(
            model_name='reciennacido',
            index=models.Index(condition=models.Q(('apgar_5_min__lt', 7)), fields=['apgar_5_min'], name='idx_rn_apgar5'),
        ),
        migrations.AddIndex(
            model_name='reciennacido',
            index=models.Index(fields=['destino'], name='idx_rn_destino'),
        ),
    ]
