# Generated by Django 4.2 on 2025-12-07 01:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neonatologia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciennacido',
            name='apego_piel_a_piel',
            field=models.BooleanField(default=False, help_text='Se realizó apego piel a piel'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='circunferencia_abdominal_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Circunferencia abdominal en cm', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(45.0)]),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='circunferencia_toracica_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Circunferencia torácica en cm', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(45.0)]),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='edad_gestacional_capurro',
            field=models.IntegerField(blank=True, help_text='Edad gestacional calculada por método Capurro', null=True, validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(45)]),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='estado_al_nacer',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('muerto', 'Muerto'), ('mortinato', 'Mortinato')], default='vivo', max_length=20),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='hora_primera_lactancia',
            field=models.TimeField(blank=True, help_text='Hora de primera lactancia', null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='hora_vacuna_hepatitis_b',
            field=models.TimeField(blank=True, help_text='Hora de administración de vacuna Hepatitis B', null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='hora_vitamina_k',
            field=models.TimeField(blank=True, help_text='Hora de administración de vitamina K', null=True),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='lactancia_inmediata',
            field=models.BooleanField(default=False, help_text='Lactancia materna inmediata en sala de parto'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='motivo_traslado',
            field=models.TextField(blank=True, help_text='Motivo de traslado a otro centro o UCI'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='profilaxis_ocular',
            field=models.BooleanField(default=False, help_text='Profilaxis ocular administrada (tetraciclina/eritromicina)'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='tiempo_apego_minutos',
            field=models.IntegerField(blank=True, help_text='Tiempo de apego piel a piel en minutos', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='tiempo_pinzamiento_cordon_segundos',
            field=models.IntegerField(blank=True, help_text='Tiempo de pinzamiento del cordón en segundos', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='vacuna_hepatitis_b',
            field=models.BooleanField(default=False, help_text='Vacuna Hepatitis B administrada'),
        ),
        migrations.AddField(
            model_name='reciennacido',
            name='vitamina_k_administrada',
            field=models.BooleanField(default=False, help_text='Vitamina K administrada'),
        ),
        migrations.AddField(
            model_name='seguimientoneonatal',
            name='deposiciones',
            field=models.BooleanField(default=False, help_text='Presenta deposiciones'),
        ),
        migrations.AddField(
            model_name='seguimientoneonatal',
            name='diuresis',
            field=models.BooleanField(default=False, help_text='Presenta diuresis'),
        ),
        migrations.AddField(
            model_name='seguimientoneonatal',
            name='numero_diuresis',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='seguimientoneonatal',
            name='saturacion_oxigeno',
            field=models.IntegerField(blank=True, help_text='Saturación de oxígeno en %', null=True, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='seguimientoneonatal',
            name='tipo_deposicion',
            field=models.CharField(blank=True, help_text='Tipo de deposición (meconio, transición, normal)', max_length=50),
        ),
        migrations.AddField(
            model_name='seguimientoneonatal',
            name='volumen_alimentacion_ml',
            field=models.IntegerField(blank=True, help_text='Volumen de alimentación en ml', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='seguimientoneonatal',
            name='tipo_alimentacion',
            field=models.CharField(blank=True, choices=[('lactancia_materna', 'Lactancia Materna Exclusiva'), ('formula', 'Fórmula'), ('mixta', 'Mixta'), ('sonda', 'Sonda'), ('parenteral', 'Parenteral')], max_length=30),
        ),
        migrations.CreateModel(
            name='ComplicacionNeonatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cie10', models.CharField(help_text='Código CIE-10 de la complicación', max_length=10)),
                ('descripcion_cie10', models.CharField(help_text='Descripción según CIE-10', max_length=500)),
                ('tipo', models.CharField(choices=[('distress_respiratorio', 'Síndrome Distress Respiratorio'), ('hipoglicemia', 'Hipoglicemia Neonatal'), ('ictericia', 'Ictericia/Hiperbilirrubinemia'), ('sepsis', 'Sepsis Neonatal'), ('asfixia', 'Asfixia Perinatal'), ('aspiracion_meconio', 'Aspiración de Meconio'), ('malformacion', 'Malformación Congénita'), ('prematurez', 'Complicación de Prematurez'), ('otra', 'Otra Complicación')], max_length=30)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('critica', 'Crítica')], default='leve', max_length=20)),
                ('tratamiento_realizado', models.TextField(blank=True, help_text='Descripción del tratamiento realizado')),
                ('requirio_uci', models.BooleanField(default=False, help_text='¿Requirió ingreso a UCI Neonatal?')),
                ('requirio_ventilacion', models.BooleanField(default=False, help_text='¿Requirió ventilación mecánica?')),
                ('requirio_fototerapia', models.BooleanField(default=False, help_text='¿Requirió fototerapia?')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complicaciones_neonatales', to='neonatologia.reciennacido')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complicación Neonatal',
                'verbose_name_plural': 'Complicaciones Neonatales',
                'db_table': 'complicacion_neonatal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APGARDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField(choices=[(1, '1 minuto'), (5, '5 minutos'), (10, '10 minutos')])),
                ('frecuencia_cardiaca', models.IntegerField(help_text='0=Ausente, 1=<100 lpm, 2=>100 lpm', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('esfuerzo_respiratorio', models.IntegerField(help_text='0=Ausente, 1=Lento/irregular, 2=Bueno/llanto', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('tono_muscular', models.IntegerField(help_text='0=Flácido, 1=Flexión leve, 2=Movimiento activo', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('irritabilidad_refleja', models.IntegerField(help_text='0=Sin respuesta, 1=Mueca, 2=Llanto/tos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('color_piel', models.IntegerField(help_text='0=Azul/pálido, 1=Cuerpo rosado/extremidades azules, 2=Rosado', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recien_nacido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apgar_detalles', to='neonatologia.reciennacido')),
                ('usuario_evaluador', models.ForeignKey(help_text='Profesional que realiza la evaluación', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'APGAR Detallado',
                'verbose_name_plural': 'APGAR Detallados',
                'db_table': 'apgar_detalle',
                'ordering': ['minuto'],
            },
        ),
        migrations.AddIndex(
            model_name='complicacionneonatal',
            index=models.Index(fields=['recien_nacido', 'tipo'], name='idx_complicacion_rn_tipo'),
        ),
        migrations.AddIndex(
            model_name='complicacionneonatal',
            index=models.Index(fields=['codigo_cie10'], name='idx_complicacion_rn_cie10'),
        ),
        migrations.AddIndex(
            model_name='apgardetalle',
            index=models.Index(fields=['recien_nacido', 'minuto'], name='idx_apgar_rn_minuto'),
        ),
        migrations.AlterUniqueTogether(
            name='apgardetalle',
            unique_together={('recien_nacido', 'minuto')},
        ),
    ]
