# Generated by Django 4.2 on 2025-11-30 22:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fur', models.DateField(help_text='Fecha Última Regla')),
                ('fecha_primer_control', models.DateField(blank=True, null=True)),
                ('num_controles_realizados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('grupo_sanguineo', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=5)),
                ('factor_rh', models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('negativo', 'Negativo')], max_length=10)),
                ('hemoglobina_g_dl', models.DecimalField(blank=True, decimal_places=1, help_text='Hemoglobina en g/dL', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(6.0), django.core.validators.MaxValueValidator(20.0)])),
                ('glicemia_mg_dl', models.IntegerField(blank=True, help_text='Glicemia en mg/dL', null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(400)])),
                ('num_gestas_previas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('num_partos_previos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('num_cesareas_previas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('num_abortos_previos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('embarazo_gemelar', models.BooleanField(default=False)),
                ('hipertension', models.BooleanField(default=False)),
                ('diabetes_gestacional', models.BooleanField(default=False)),
                ('preeclampsia', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_prenatales', to='pacientes.pacientemadre')),
            ],
            options={
                'verbose_name': 'Control Prenatal',
                'verbose_name_plural': 'Controles Prenatales',
                'db_table': 'control_prenatal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_parto', models.DateField()),
                ('hora_parto', models.TimeField()),
                ('edad_gestacional_semanas', models.IntegerField(help_text='Edad gestacional en semanas', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(45)])),
                ('edad_gestacional_dias', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('tipo_parto', models.CharField(choices=[('eutocico', 'Eutócico (Vaginal Normal)'), ('cesarea_electiva', 'Cesárea Electiva'), ('cesarea_urgencia', 'Cesárea de Urgencia'), ('forceps', 'Fórceps'), ('ventosa', 'Ventosa')], max_length=30)),
                ('presentacion', models.CharField(choices=[('cefalica', 'Cefálica'), ('podalica', 'Podálica'), ('transversa', 'Transversa')], max_length=20)),
                ('inicio_trabajo_parto', models.CharField(choices=[('espontaneo', 'Espontáneo'), ('inducido', 'Inducido'), ('cesarea_sin_trabajo', 'Cesárea sin Trabajo de Parto')], max_length=30)),
                ('grupo_robson', models.IntegerField(help_text='Clasificación OMS Robson (1-10)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('primigesta', models.BooleanField(default=False)),
                ('multigesta', models.BooleanField(default=False)),
                ('cicatriz_uterina', models.BooleanField(default=False, help_text='Cesárea previa u otra cirugía uterina')),
                ('rotura_membranas', models.CharField(blank=True, choices=[('espontanea', 'Espontánea'), ('artificial', 'Artificial'), ('integras', 'Íntegras')], max_length=20)),
                ('liquido_amniotico', models.CharField(blank=True, choices=[('claro', 'Claro'), ('meconial', 'Meconial'), ('sanguinolento', 'Sanguinolento')], max_length=20)),
                ('anestesia', models.CharField(blank=True, choices=[('ninguna', 'Ninguna'), ('epidural', 'Epidural'), ('raquidea', 'Raquídea'), ('general', 'General')], max_length=20)),
                ('hemorragia_postparto', models.BooleanField(default=False)),
                ('hemorragia_ml', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('desgarro_perineal', models.CharField(choices=[('ninguno', 'Ninguno'), ('grado_1', 'Grado I'), ('grado_2', 'Grado II'), ('grado_3', 'Grado III'), ('grado_4', 'Grado IV')], default='ninguno', max_length=20)),
                ('episiotomia', models.BooleanField(default=False)),
                ('indicacion_cesarea', models.CharField(choices=[('no_aplica', 'No Aplica'), ('sufrimiento_fetal', 'Sufrimiento Fetal'), ('desproporcion_cefalopelvica', 'Desproporción Cefalopélvica'), ('distocia_trabajo_parto', 'Distocia de Trabajo de Parto'), ('cesarea_previa', 'Cesárea Previa'), ('presentacion_anomala', 'Presentación Anómala'), ('placenta_previa', 'Placenta Previa'), ('desprendimiento_placenta', 'Desprendimiento de Placenta'), ('preeclampsia_severa', 'Preeclampsia Severa'), ('otra', 'Otra')], default='no_aplica', max_length=40)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('control_prenatal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='obstetricia.controlprenatal')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='pacientes.pacientemadre')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'db_table': 'parto',
                'ordering': ['-fecha_parto', '-hora_parto'],
            },
        ),
        migrations.CreateModel(
            name='ExamenPrenatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_examen', models.CharField(choices=[('vih', 'VIH'), ('vdrl', 'VDRL (Sífilis)'), ('hepatitis_b', 'Hepatitis B'), ('streptococo_b', 'Streptococo Grupo B'), ('hemograma', 'Hemograma'), ('grupo_rh', 'Grupo y RH'), ('glicemia', 'Glicemia'), ('urocultivo', 'Urocultivo')], max_length=30)),
                ('resultado', models.CharField(choices=[('negativo', 'Negativo'), ('positivo', 'Positivo'), ('no_reactivo', 'No Reactivo'), ('reactivo', 'Reactivo'), ('no_realizado', 'No Realizado'), ('pendiente', 'Pendiente')], max_length=30)),
                ('fecha_examen', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control_prenatal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='obstetricia.controlprenatal')),
            ],
            options={
                'verbose_name': 'Examen Prenatal',
                'verbose_name_plural': 'Exámenes Prenatales',
                'db_table': 'examen_prenatal',
                'ordering': ['-fecha_examen'],
            },
        ),
        migrations.AddIndex(
            model_name='parto',
            index=models.Index(fields=['-fecha_parto'], name='idx_parto_fecha'),
        ),
        migrations.AddIndex(
            model_name='parto',
            index=models.Index(fields=['grupo_robson'], name='idx_parto_robson'),
        ),
        migrations.AddIndex(
            model_name='parto',
            index=models.Index(fields=['tipo_parto'], name='idx_parto_tipo'),
        ),
        migrations.AddIndex(
            model_name='examenprenatal',
            index=models.Index(fields=['tipo_examen', 'resultado'], name='idx_examen_tipo_resultado'),
        ),
        migrations.AddIndex(
            model_name='examenprenatal',
            index=models.Index(fields=['-fecha_examen'], name='idx_examen_fecha'),
        ),
    ]
