# Generated by Django 4.2 on 2025-12-07 01:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obstetricia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloVIH',
            fields=[
                ('parto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='protocolo_vih', serialize=False, to='obstetricia.parto')),
                ('activado', models.BooleanField(default=False, help_text='Protocolo activado automáticamente')),
                ('fecha_activacion', models.DateTimeField(blank=True, help_text='Fecha y hora de activación del protocolo', null=True)),
                ('arv_madre_durante_parto', models.BooleanField(default=False, help_text='ARV administrado a madre durante parto')),
                ('arv_rn_administrado', models.BooleanField(default=False, help_text='ARV administrado a RN (profilaxis)')),
                ('lactancia_suspendida', models.BooleanField(default=False, help_text='Lactancia materna suspendida (reemplazo fórmula)')),
                ('cesarea_electiva_recomendada', models.BooleanField(default=False, help_text='Cesárea electiva recomendada según carga viral')),
                ('carga_viral_materna', models.IntegerField(blank=True, help_text='Carga viral materna (copias/ml)', null=True)),
                ('notificado_infectologia', models.BooleanField(default=False, help_text='Servicio de infectología notificado')),
                ('notificado_neonatologia', models.BooleanField(default=False, help_text='Neonatología notificada para seguimiento RN')),
                ('seguimiento_programado', models.BooleanField(default=False, help_text='Seguimiento programado para RN (test PCR, serología)')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protocolo VIH Perinatal',
                'verbose_name_plural': 'Protocolos VIH Perinatales',
                'db_table': 'protocolo_vih',
            },
        ),
        migrations.AddField(
            model_name='parto',
            name='acompanamiento_parto',
            field=models.BooleanField(default=False, help_text='Acompañamiento durante el parto'),
        ),
        migrations.AddField(
            model_name='parto',
            name='acompanamiento_prepartos',
            field=models.BooleanField(default=False, help_text='Acompañamiento durante prepartos'),
        ),
        migrations.AddField(
            model_name='parto',
            name='acompanamiento_rn',
            field=models.BooleanField(default=False, help_text='Acompañamiento durante atención RN'),
        ),
        migrations.AddField(
            model_name='parto',
            name='alumbramiento',
            field=models.CharField(choices=[('completo', 'Completo'), ('incompleto', 'Incompleto'), ('manual', 'Manual'), ('instrumental', 'Instrumental')], default='completo', max_length=20),
        ),
        migrations.AddField(
            model_name='parto',
            name='derivacion_saip',
            field=models.BooleanField(default=False, help_text='Derivación a SAIP (Sistema Atención Integral Violencia)'),
        ),
        migrations.AddField(
            model_name='parto',
            name='desgarro_cervical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='duracion_periodo_expulsivo_minutos',
            field=models.IntegerField(blank=True, help_text='Duración del periodo expulsivo en minutos', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(240)]),
        ),
        migrations.AddField(
            model_name='parto',
            name='duracion_trabajo_parto_minutos',
            field=models.IntegerField(blank=True, help_text='Duración total del trabajo de parto en minutos', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2880)]),
        ),
        migrations.AddField(
            model_name='parto',
            name='hora_inicio_trabajo_parto',
            field=models.TimeField(blank=True, help_text='Hora de inicio del trabajo de parto', null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='hora_rotura_membranas',
            field=models.TimeField(blank=True, help_text='Hora de rotura de membranas', null=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='indicacion_cesarea_otra',
            field=models.TextField(blank=True, help_text='Descripción si indicación es "otra"'),
        ),
        migrations.AddField(
            model_name='parto',
            name='inversion_uterina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='lugar_atencion',
            field=models.CharField(choices=[('sala_parto', 'Sala de Parto'), ('pabellon', 'Pabellón Quirúrgico'), ('urgencia', 'Servicio de Urgencia'), ('domicilio', 'Domicilio'), ('traslado', 'Durante Traslado')], default='sala_parto', max_length=20),
        ),
        migrations.AddField(
            model_name='parto',
            name='nombre_acompanante',
            field=models.CharField(blank=True, help_text='Nombre del acompañante', max_length=200),
        ),
        migrations.AddField(
            model_name='parto',
            name='parentesco_acompanante',
            field=models.CharField(blank=True, help_text='Parentesco del acompañante', max_length=100),
        ),
        migrations.AddField(
            model_name='parto',
            name='parto_agua',
            field=models.BooleanField(default=False, help_text='Parto en agua'),
        ),
        migrations.AddField(
            model_name='parto',
            name='parto_vertical',
            field=models.BooleanField(default=False, help_text='Parto en posición vertical'),
        ),
        migrations.AddField(
            model_name='parto',
            name='peso_placenta_gramos',
            field=models.IntegerField(blank=True, help_text='Peso de la placenta en gramos', null=True, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(1500)]),
        ),
        migrations.AddField(
            model_name='parto',
            name='placenta_completa',
            field=models.BooleanField(default=True, help_text='Placenta completa sin retención'),
        ),
        migrations.AddField(
            model_name='parto',
            name='plan_parto_observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='parto',
            name='plan_parto_respetado',
            field=models.BooleanField(default=True, help_text='¿Se respetó el plan de parto?'),
        ),
        migrations.AddField(
            model_name='parto',
            name='profesional_atiende_nombre',
            field=models.CharField(blank=True, help_text='Nombre del profesional que atiende', max_length=200),
        ),
        migrations.AddField(
            model_name='parto',
            name='profesional_atiende_rut',
            field=models.CharField(blank=True, help_text='RUT del profesional que atiende el parto', max_length=12),
        ),
        migrations.AddField(
            model_name='parto',
            name='retencion_placentaria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='ruptura_uterina',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parto',
            name='sospecha_violencia',
            field=models.BooleanField(default=False, help_text='Sospecha de violencia intrafamiliar'),
        ),
        migrations.AddField(
            model_name='parto',
            name='tiene_plan_parto',
            field=models.BooleanField(default=False, help_text='¿Paciente tiene plan de parto?'),
        ),
        migrations.CreateModel(
            name='ComplicacionMaterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cie10', models.CharField(help_text='Código CIE-10 de la complicación', max_length=10)),
                ('descripcion_cie10', models.CharField(help_text='Descripción según CIE-10', max_length=500)),
                ('tipo', models.CharField(choices=[('hemorragia', 'Hemorragia Postparto'), ('preeclampsia', 'Preeclampsia/Eclampsia'), ('sepsis', 'Sepsis Puerperal'), ('ruptura_uterina', 'Ruptura Uterina'), ('embolia', 'Embolia'), ('shock', 'Shock Hipovolemicó/Séptico'), ('desgarro_grave', 'Desgarro Grado III-IV'), ('otra', 'Otra Complicación')], max_length=30)),
                ('severidad', models.CharField(choices=[('leve', 'Leve'), ('moderada', 'Moderada'), ('grave', 'Grave'), ('critica', 'Crítica')], default='leve', max_length=20)),
                ('tratamiento_realizado', models.TextField(blank=True, help_text='Descripción del tratamiento realizado')),
                ('requirio_uci', models.BooleanField(default=False, help_text='¿Requirió ingreso a UCI?')),
                ('requirio_transfusion', models.BooleanField(default=False, help_text='¿Requirió transfusión sanguínea?')),
                ('requirio_cirugia', models.BooleanField(default=False, help_text='¿Requirió cirugía adicional?')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complicaciones_maternas', to='obstetricia.parto')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complicación Materna',
                'verbose_name_plural': 'Complicaciones Maternas',
                'db_table': 'complicacion_materna',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complicacionmaterna',
            index=models.Index(fields=['parto', 'tipo'], name='idx_complicacion_parto_tipo'),
        ),
        migrations.AddIndex(
            model_name='complicacionmaterna',
            index=models.Index(fields=['codigo_cie10'], name='idx_complicacion_cie10'),
        ),
    ]
