# Generated by Django 4.2 on 2025-12-08 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('obstetricia', '0002_protocolovih_parto_acompanamiento_parto_and_more'),
        ('neonatologia', '0002_reciennacido_apego_piel_a_piel_and_more'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APGAR_CRITICO', 'APGAR Crítico (< 7)'), ('BAJO_PESO', 'Recién Nacido Bajo Peso (< 2500g)'), ('REANIMACION', 'Reanimación Requerida'), ('HEMORRAGIA', 'Hemorragia Materna'), ('PREECLAMPSIA', 'Pre-eclampsia/Eclampsia'), ('SUFRIMIENTO_FETAL', 'Sufrimiento Fetal'), ('CESAREA_EMERGENCIA', 'Cesárea de Emergencia'), ('UCI_NEONATAL', 'Derivación UCI Neonatal'), ('COMPLICACION_MADRE', 'Complicación Materna Grave'), ('COMPLICACION_RN', 'Complicación RN Grave')], max_length=30, verbose_name='Tipo de Alerta')),
                ('nivel_urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=10, verbose_name='Nivel de Urgencia')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('EN_ATENCION', 'En Atención'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], default='ACTIVA', max_length=15, verbose_name='Estado')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_hora_alerta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Alerta')),
                ('fecha_hora_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Atención')),
                ('fecha_hora_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='pacientes.pacientemadre')),
                ('parto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='obstetricia.parto')),
                ('recien_nacido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='neonatologia.reciennacido')),
                ('usuario_atiende', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que atiende')),
                ('usuario_genera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_generadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que genera')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alertas',
                'ordering': ['-fecha_hora_alerta', '-nivel_urgencia'],
            },
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['estado', '-fecha_hora_alerta'], name='alertas_estado_04bed9_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['nivel_urgencia', 'estado'], name='alertas_nivel_u_fad3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='alerta',
            index=models.Index(fields=['tipo', 'estado'], name='alertas_tipo_fd0354_idx'),
        ),
    ]
